apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reserve-service-ingress
  labels:
    app: reserve-service
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://test.s7age.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"

    # HSTS 적용
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"

    # WebSocket
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/enable-websocket: "true"

spec:
  ingressClassName: nginx
  rules:
  - host: test.api.s7age.com
    http:
      paths:
      # REST API
      - path: /api/v1/reserve
        pathType: Prefix
        backend:
          service:
            name: reserve-service
            port:
              number: 8080
      # WebSocket 엔드포인트
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: reserve-service
            port:
              number: 8080
