plugin: amazon.aws.aws_ec2
regions:
  - ap-northeast-2

include_resource_tags: false

filters:
  instance-state-name: running
  tag:Role: "monitoring" 
  tag:Project: "prod_master"
  
hostnames:
  - instance-id

keyed_groups:
  - key: tags.Role | default('default')
    prefix: ""
    separator: ""


compose:
  ansible_connection: "'aws_ssm'"
  ansible_aws_ssm_region: "'ap-northeast-2'"
  ansible_user: "'ubuntu'"
  ansible_aws_ssm_bucket_name: "'stage-ansible-ssm-tmp'"
