- name: Install or upgrade k3s agent with fixed version
  become: true
  shell: |
    curl -sfL {{ k3s_install_url }} | \
    INSTALL_K3S_VERSION={{ k3s_version }} \
    K3S_URL=https://{{ k3s_master_ip }}:6443 \
    K3S_TOKEN={{ k3s_token }} \
    sh -
