plugin: amazon.aws.aws_ec2
regions:
  - ap-northeast-2

include_resource_tags: false

filters:
  instance-state-name: running
  tag:Project: "dev_worker" 

hostnames:
  - instance-id

groups:
  worker: true


compose:
  ansible_connection: "'aws_ssm'"
  ansible_aws_ssm_region: "'ap-northeast-2'"
  ansible_user: "'ubuntu'"
  ansible_aws_ssm_bucket_name: "'stage-ansible-ssm-tmp'"

  