- name: Get k8s node name (hostname) on worker
  command: hostname
  register: node_hostname
  changed_when: false

- name: Apply DB label (run kubectl on master)
  shell: |
    kubectl label node {{ node_hostname.stdout }} {{ mysql_node_label_key }}={{ mysql_node_label_value }} --overwrite
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  delegate_to: "{{ groups['master'][0] }}"